//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentPlans
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentId { get; set; }
        public int PlanId { get; set; }
        public System.DateTime PaymentFromDate { get; set; }
        public System.DateTime PaymentToDate { get; set; }
        public decimal PaymentAmount { get; set; }
    }
}
