//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentPlans
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanMaster
    {
        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public decimal PlanAmount { get; set; }
        public decimal ServiceTaxAmount { get; set; }
        public decimal ServiceTax { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
